// export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST";
// export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
// export const GET_BLOG_FAIL = "GET_BLOG_FAIL"; 

export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_DEFAULT = "GET_BLOG_DEFAULT";

/*About*/

export const GET_ABOUT_SUCCESS = "GET_ABOUT_SUCCESS";
export const GET_ABOUT_DEFAULT = "GET_ABOUT_DEFAULT";

/*Service*/

export const GET_SERVICE_REQUEST = "GET_SERVICE_REQUEST";
export const GET_SERVICE_SUCCESS = "GET_SERVICE_SUCCESS";
export const GET_SERVICE_FAIL = "GET_SERVICE_FAIL";

/*Logo*/

export const GET_LOGO_SUCCESS = "GET_LOGO_SUCCESS";
export const GET_LOGO_DEFAULT = "GET_LOGO_DEFAULT";

/*Bottom Services*/

export const GET_BOTTOM_SERVICE_SUCCESS = "GET_BOTTOM_SERVICE_SUCCESS";
export const GET_BOTTOM_SERVICE_DEFAULT = "GET_BOTTOM_SERVICE_DEFAULT";

